version: "3"

volumes:
  mysql_data:
    driver: local

services:
  api_server:
    container_name: "api_server"
    build: ./
    volumes:
      - ./api_server:/workdir
    ports:
      - 8888:8888

  api_client:
    container_name: "api_client"
    build: ./
    volumes:
      - ./api_client:/workdir
    ports:
      - 8889:8888

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    image: jboss/keycloak:latest
    container_name: "keycloak"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - mysql
